# Anschauungsmaterial

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
import numpy as np
corpus = ["Anwalt wird als Dieb bezeichnet",
        "Anwalt der scheintoten Frau",
        "Dieb gibt sich als Frau aus",
        "Dieb geht zum Anwalt und trifft einen anderen Dieb"]

In [2]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
sw = stopwords.words('german')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\elguj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
vectorizerCount = CountVectorizer()
vocabularyCount = vectorizerCount.fit_transform(corpus)
print(vectorizerCount.vocabulary_)
print(vocabularyCount)

{'anwalt': 2, 'wird': 15, 'als': 0, 'dieb': 6, 'bezeichnet': 4, 'der': 5, 'scheintoten': 11, 'frau': 8, 'gibt': 10, 'sich': 12, 'aus': 3, 'geht': 9, 'zum': 16, 'und': 14, 'trifft': 13, 'einen': 7, 'anderen': 1}
  (0, 2)	1
  (0, 15)	1
  (0, 0)	1
  (0, 6)	1
  (0, 4)	1
  (1, 2)	1
  (1, 5)	1
  (1, 11)	1
  (1, 8)	1
  (2, 0)	1
  (2, 6)	1
  (2, 8)	1
  (2, 10)	1
  (2, 12)	1
  (2, 3)	1
  (3, 2)	1
  (3, 6)	2
  (3, 9)	1
  (3, 16)	1
  (3, 14)	1
  (3, 13)	1
  (3, 7)	1
  (3, 1)	1


In [14]:
vectorizerCount = CountVectorizer(stop_words=sw, min_df=2)
vocabularyCount = vectorizerCount.fit_transform(corpus)
print(vectorizerCount.vocabulary_)
print(vocabularyCount)

{'anwalt': 0, 'dieb': 1, 'frau': 2}
  (0, 0)	1
  (0, 1)	1
  (1, 0)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (3, 0)	1
  (3, 1)	2


In [15]:
array=vectorizerCount.transform(corpus).toarray()
print(array)

[[1 1 0]
 [1 0 1]
 [0 1 1]
 [1 2 0]]


In [16]:
vectorizerTfidf = TfidfVectorizer(max_df=1.0,min_df=2,norm=False, use_idf=True, sublinear_tf=False, stop_words=sw)
vocabularyTfidf = vectorizerTfidf.fit_transform(corpus)
print(vectorizerTfidf.vocabulary_)
print(vocabularyTfidf)

{'anwalt': 0, 'dieb': 1, 'frau': 2}
  (0, 1)	1.2231435513142097
  (0, 0)	1.2231435513142097
  (1, 2)	1.5108256237659907
  (1, 0)	1.2231435513142097
  (2, 2)	1.5108256237659907
  (2, 1)	1.2231435513142097
  (3, 1)	2.4462871026284194
  (3, 0)	1.2231435513142097


In [7]:
vectorizerTfidf = TfidfVectorizer(max_df=1.0,min_df=2, norm='l2', use_idf=True, sublinear_tf=False, stop_words=sw)
vocabularyTfidf = vectorizerTfidf.fit_transform(corpus)
print(vectorizerTfidf.vocabulary_)
print(vocabularyTfidf)

{'anwalt': 0, 'dieb': 1, 'frau': 2}
  (0, 1)	0.7071067811865475
  (0, 0)	0.7071067811865475
  (1, 2)	0.7772211620785797
  (1, 0)	0.6292275146695526
  (2, 2)	0.7772211620785797
  (2, 1)	0.6292275146695526
  (3, 1)	0.8944271909999159
  (3, 0)	0.4472135954999579


In [25]:
vectorizerTfidf = TfidfVectorizer(max_df=1.0,min_df=2,norm=False, use_idf=True, sublinear_tf=False, stop_words=sw)
vectorizerCount = CountVectorizer()
vocabularyTfidf = vectorizerTfidf.fit_transform(corpus)
vocabularyCount = vectorizerCount.fit_transform(corpus)
array=vectorizerCount.transform(corpus).toarray()
print(vectorizerCount.vocabulary_)
print(vectorizerTfidf.vocabulary_)
print(vocabularyTfidf)
print(vocabularyCount)
print(array)

{'anwalt': 2, 'wird': 15, 'als': 0, 'dieb': 6, 'bezeichnet': 4, 'der': 5, 'scheintoten': 11, 'frau': 8, 'gibt': 10, 'sich': 12, 'aus': 3, 'geht': 9, 'zum': 16, 'und': 14, 'trifft': 13, 'einen': 7, 'anderen': 1}
{'anwalt': 0, 'dieb': 1, 'frau': 2}
  (0, 1)	1.2231435513142097
  (0, 0)	1.2231435513142097
  (1, 2)	1.5108256237659907
  (1, 0)	1.2231435513142097
  (2, 2)	1.5108256237659907
  (2, 1)	1.2231435513142097
  (3, 1)	2.4462871026284194
  (3, 0)	1.2231435513142097
  (0, 2)	1
  (0, 15)	1
  (0, 0)	1
  (0, 6)	1
  (0, 4)	1
  (1, 2)	1
  (1, 5)	1
  (1, 11)	1
  (1, 8)	1
  (2, 0)	1
  (2, 6)	1
  (2, 8)	1
  (2, 10)	1
  (2, 12)	1
  (2, 3)	1
  (3, 2)	1
  (3, 6)	2
  (3, 9)	1
  (3, 16)	1
  (3, 14)	1
  (3, 13)	1
  (3, 7)	1
  (3, 1)	1
[[1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0]
 [1 0 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0]
 [0 1 1 0 0 0 2 1 0 1 0 0 0 1 1 0 1]]
